# Generated by Django 5.0.4 on 2024-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
