# Generated by Django 5.0.4 on 2024-05-03 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_expense_category_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
